organizer/urls.py
from django.contrib import admin
from django.urls import path,include

from .views import HomeView
from student import urls as studentURL
from examination import urls as examURL
from users import urls as userURL
from result import urls as resultURL
from study import urls as studyURL

urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('student/',include(studentURL)),
    path('exam/', include(examURL)),
    path('user/', include(userURL, namespace='dj-auth')),
    path('result/', include(resultURL)),
    path('study/', include(studyURL))
]

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import  RedirectView, TemplateView
from .views import LoginView, LogoutView, PasswordChangeDoneView, PasswordChangeView, \
                    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, \
                    DisableAccount, ActivateAccount, CreateAccount, ResendActivationEmail

app_name = 'users'

urlpatterns = [
    path('',RedirectView.as_view(pattern_name='dj-auth:login', permanent = False)),

    path('login/',LoginView.as_view(),name="login"),
    path('logout/',LogoutView.as_view(),name="logout"),

    path('password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('password/',RedirectView.as_view(pattern_name='dj-auth:password_reset', permanent=False)),

    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),
    path('activate/resend/', ResendActivationEmail.as_view(), name='resend_activation'),
    path('activate/', RedirectView.as_view(pattern_name='dj-auth:resend_activation', permanent=False)),
    path('create/', CreateAccount.as_view(), name='create'),
    path('create/done/', TemplateView.as_view(template_name='users/user_create_done.html'), name='create_done'),
    path('disable/', DisableAccount.as_view(),name='disable'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from config.roles import ROLES_CHOICES, STUDENT_ROLE

# Create your models here.

class User(AbstractUser):
    role = models.CharField("Role",max_length= 10, choices=ROLES_CHOICES, default=STUDENT_ROLE)

users/forms.py
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm
from .utils import  ActivationMailFormMixin
from django.contrib.auth import get_user_model
import logging
from django import forms
from django.core.exceptions import ValidationError


logger = logging.getLogger(__name__)
class UserCraeationForm(ActivationMailFormMixin, BaseUserCreationForm):

    mail_validation_error = (
        'User created. Could not send activation email.' 
        ' Please try again later. (Sorry!)')

    class Meta(BaseUserCreationForm.Meta):

        model = get_user_model()
        fields = ('username','email',)

    def clean_username(self):
        username = self.cleaned_data['username']
        disallowed = ('activate', 'create', 'disable', 'login', 'logout', 'password', 'student','parentProfile')
        if username in disallowed:
            raise ValidationError("A user with that username already exists.")
        return username

    def save(self, **kwargs):
        user = super().save(commit=False)
        if not user.pk:
            user.is_active = False
            send_mail = True
        else:
            send_mail = False
        user.save()
        self.save_m2m()
        if send_mail:
            self.send_mail(user=user,**kwargs)
        return user

class ResendActivationEmailForm(ActivationMailFormMixin, forms.Form):

    mail_validation_error = (
        'Could not re-send activation email.' 
        ' Please try again later. (Sorry!)')

    email = forms.EmailField()

    def save(self, **kwargs):
        User = get_user_model()
        try:
            user = User.objects.get(email=self.cleaned_data['email'])
        except:
            logger.warning('Resend Activation: No user with email : {} .'.format(self.cleaned_data['email']))
            return None
        self.send_mail(user=user, **kwargs)
        return user

            

users/views.py
from django.shortcuts import render
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse_lazy
from django.contrib.auth import get_user,get_user_model,logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.views import View
from django.urls import reverse_lazy
from .forms import UserCraeationForm, ResendActivationEmailForm
from .utils import  MailContextViewMixin
from django.views.decorators.debug import sensitive_post_parameters
from django.contrib.messages import error, success
from django.views.decorators.cache import never_cache
from django.utils.encoding import force_text
from django.utils.http import  urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator as token_generator
from organizer import settings

class LoginView(auth_views.LoginView):
    template_name = 'users/login.html'

class LogoutView(auth_views.LogoutView):

    template_name = 'users/logout.html'
    extra_context = {'form' : AuthenticationForm}


class PasswordChangeView(auth_views.PasswordChangeView):

    template_name = 'users/password_change_form.html'
    success_url = reverse_lazy('dj-auth:password_change_done')


class PasswordChangeDoneView(auth_views.PasswordChangeDoneView):
    template_name = 'users/password_change_done.html'


class PasswordResetView(auth_views.PasswordResetView):

    template_name = 'users/password_reset_form.html'
    email_template_name = 'users/password_reset_email.txt'
    subject_template_name = 'users/password_reset_subject.txt'
    success_url = reverse_lazy('dj-auth:password_reset_done')

class PasswordResetDoneView(auth_views.PasswordResetDoneView):

    template_name = 'users/password_reset_done.html'


class  PasswordResetConfirmView(auth_views.PasswordResetConfirmView):

    success_url = reverse_lazy('dj-auth:password_reset_complete')
    template_name = 'users/password_reset_confirm.html'


class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):

    template_name = 'users/password_reset_complete.html'
    extra_context = {'form': AuthenticationForm }


class DisableAccount(View):

    success_url = settings.LOGIN_REDIRECT_URL
    template_name = 'users/user_confirm_delete.html'

    @method_decorator(csrf_protect)
    @method_decorator(login_required)
    def get(self, request):
        return TemplateResponse(request,self.template_name)

    def post(self,request):
        user = get_user(request)
        user.set_unusable_password()
        user.is_active = False
        user.save()
        logout(request)
        return redirect(self.success_url)


class CreateAccount(MailContextViewMixin, View):

    form_class = UserCraeationForm
    success_url =  reverse_lazy('dj-auth:create_done')
    template_name = 'users/user_create.html'


    @method_decorator(csrf_protect)
    def get(self, request):
        return TemplateResponse(request, self.template_name, context={'form' : self.form_class})


    @method_decorator(csrf_protect)
    @method_decorator(sensitive_post_parameters('password1', 'password2'))
    def post(self, request):
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            bound_form.save(**self.get_save_kwargs(request))
            if bound_form.mail_sent:
                return redirect(self.success_url)
            else:
                errs = (bound_form.non_field_errors())
                for err in errs:
                    error(request, err)
                return redirect('dj-auth:resend_activation')
        return TemplateResponse(request, self.template_name, context={'form' : bound_form})

class ActivateAccount(View):

    success_url = reverse_lazy('dj-auth:login')
    template_name = 'users/user_activate.html'

    @method_decorator(never_cache)
    def get(self, request, uidb64, token):
        
        User = get_user_model()
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk = uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist) :
            user = None
        if(user is not None and token_generator.check_token(user,token)):
            user.is_active = True
            user.save()
            success(request, 'User Activated! You may now login!')
            return redirect(self.success_url)
        else:
            return TemplateResponse(request, self.template_name)

class ResendActivationEmail(MailContextViewMixin, View):

    form_class = ResendActivationEmailForm
    success_url = reverse_lazy('dj-auth:login')
    template_name = 'users/resend_activation.html'

    @method_decorator(csrf_protect)
    def get(self, request):
        return TemplateResponse(request, self.template_name, {'form' : self.form_class})

    def post(self, request):
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            user = bound_form.save(**self.get_save_kwargs(request))
            if(user is not None and not bound_form.mail_sent):
                errs = (bound_form.non_field_errors())
                for err in errs:
                    error(request, err)
                if errs:
                    bound_form.errors.pop('__all__')
                return TemplateResponse(request, self.template_name, {'form':bound_form})
        success(request,'Activation Email Sent!')
        return redirect(self.success_url)
  

users/templates/users/base_user.html
{% extends parent_template|default:'base.html' %}

users/templates/users/login.html
{% extends parent_template|default:'users/base_user.html' %}


{% block title %}
    {{ block.super }} - Login
{% endblock title %}
    

{% block content %}
    <div>
        <div>
            {% include 'users/login_form.html' %}
        </div>
        <div>
            <ul>
                <li><a href="{% url 'dj-auth:password_reset' %}">Forgotten Password?</a></li>
                <li><a href="{% url 'dj-auth:create' %}">Register New Account</a></li>
                <li><a href="{% url 'dj-auth:resend_activation' %}">Lost Activation E-mail?</a></li>
            </ul>
        </div>
    </div>
{% endblock content %}
    

users/templates/users/login_form.html
<form action="{% url 'dj-auth:login' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    
    {% if next %}

    <input type="hidden" name="next" value="{{next}}">

    {% endif %}
        
    <button type="submit">{{ login_button|default:'Log in'}} </button>
</form>

users/templates/users/logout.html
{% extends parent_template|default:'users/base_user.html' %}

{% block title %}
    {{ block.super }} - Logged Out
{% endblock title %}
    
{% block content %}
    <div>
        <div>
            {% include 'users/login_form.html' with login_button='Log Back In' %}
        </div>
    </div>
{% endblock content %}
    

users/templates/users/password_change_done.html
{% extends parent_template|default:'users/base_user.html' %}


{% block title %}
    {{ block.super }} - Change Password
{% endblock title %}
    

{% block content %}
    <div>
        <div>
            <p>Password succesfully Changed.</p>
        </div>
    </div>
{% endblock content %}
    

users/templates/users/password_change_form.html
{% extends parent_template|default:'users/base_user.html' %}


{% block title %}
    {{ block.super }} - Change Password
{% endblock title %}
    

{% block content %}
    <div>
        <div>
            <form action="{% url 'dj-auth:password_change' %}" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Change Password</button>
            </form>
        </div>
    </div>
{% endblock content %}
    

users/templates/users/password_reset_confirm.html
{% extends parent_template|default:'users/base_user.html' %}

{% block title %}
    {{ block.super }} - Reset Password
{% endblock title %}
    

{% block content %}
    <div>
        <div>
            
            {% if validlink %}
                <p>Enter a new password below.</p>
                <form action="{{ request.path }}" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Save New Password</button>
                </form>
            {% else %}
                <p>This reset link is no longer valid.</p>
                <p>Please request a new reset email <a href="{% url 'dj-auth:password_reset' %}"> here</a>. </p>
            {% endif %}
                
        </div>
    </div>
{% endblock content %}
    

users/templates/users/password_reset_done.html
{% extends parent_template|default:'users/base_user.html' %}
{% block title %}
    {{ block.super }} - Password Reset Sent
{% endblock title %}
    

{% block content %}
    <div>
        <div>
            <p>Reset your password by email.</p>
            <p>Please check your inbox and spam box.</p>
        </div>
    </div>
{% endblock content %}
    

users/templates/users/password_reset_form.html
{% extends parent_template|default:'users/base_user.html' %}

{% block title %}
    {{ block.super }} - Reset Password
{% endblock title %}
    

{% block content %}
    <div>
        <div>
            <div>
                <p>Reset your password by email.</p>
            </div>
            <form action="{% url 'dj-auth:password_reset' %}" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Send Me Reset Instructions</button>
            </form>
        </div>
    </div>
{% endblock content %}
    

users/templates/users/resend_activation.html
{% extends parent_template|default:'users/base_user.html' %}


{% block title %}
    {{ block.super }} - Resend Activation E-mail
{% endblock title %}
    

{% block content %}
    <div>
        <div>
            <div>
                <p>Resend your account activation email.</p>
            </div>
            <form action="{% url 'dj-auth:resend_activation' %}" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Resend Activation E-mail</button>
            </form>
        </div>
    </div>
{% endblock content %}
    

users/templates/users/user_activate.html
{% extends parent_template|default:"users/base_user.html" %}

{% block title %}
{{ block.super }} - Account Activation Failed
{% endblock %}

{% block content %}
  <div>
    <div>
      <p>This activation link is no longer valid.</p>
    </div>
  </div>
{% endblock %}

users/templates/users/user_confirm_delete.html
{% extends parent_template|default:'users/base_user.html' %}

{% block title %}
    {{ block.super }} - Disable Account
{% endblock title %}
    

{% block content %}
    <div>
        <div>
            <p>Disable your account?</p>
            <p>This cannot be Undone.</p>
            <form action="{% url 'dj-auth:disable' %}" method="POST">
                {% csrf_token %}
                <button type="submit">Disable Account</button>
            </form>
        </div>
    </div>
{% endblock content %}
    

users/templates/users/user_create.html
{% extends parent_template|default:'users/base_user.html' %}


{% block title %}
    {{ block.super }} - Create Account
{% endblock title %}
    

{% block content %}
    <div>
        <div>
            <form action="{% url 'dj-auth:create' %}" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Create New Account</button>
            </form>
        </div>
        <div>
            <a href="{% url 'dj-auth:resend_activation'%}"> Lost Activation E-mail?</a>
        </div>
    </div>
{% endblock content %}
    

users/templates/users/user_create_done.html
{% extends parent_template|default:"users/base_user.html" %}

{% block title %}
{{ block.super }} - Account Created
{% endblock %}

{% block content %}
  <div>
    <div>
      <p>Your account has been created!</p>
      <p>Please check your email for
        the activation link.</p>
    </div>
  </div>
{% endblock %}