organizer/urls.py
from django.contrib import admin
from django.urls import path,include

from .views import HomeView
from student import urls as studentURL
from examination import urls as examURL
from users import urls as userURL
from result import urls as resultURL
from study import urls as studyURL

urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('student/',include(studentURL)),
    path('exam/', include(examURL)),
    path('user/', include(userURL, namespace='dj-auth')),
    path('result/', include(resultURL)),
    path('study/', include(studyURL))
]

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import  RedirectView, TemplateView
from .views import LoginView, LogoutView, PasswordChangeDoneView, PasswordChangeView, \
                    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, \
                    DisableAccount, ActivateAccount, CreateAccount, ResendActivationEmail

app_name = 'users'

urlpatterns = [
    path('',RedirectView.as_view(pattern_name='dj-auth:login', permanent = False)),

    path('login/',LoginView.as_view(),name="login"),
    path('logout/',LogoutView.as_view(),name="logout"),

    path('password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('password/',RedirectView.as_view(pattern_name='dj-auth:password_reset', permanent=False)),

    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),
    path('activate/resend/', ResendActivationEmail.as_view(), name='resend_activation'),
    path('activate/', RedirectView.as_view(pattern_name='dj-auth:resend_activation', permanent=False)),
    path('create/', CreateAccount.as_view(), name='create'),
    path('create/done/', TemplateView.as_view(template_name='users/user_create_done.html'), name='create_done'),
    path('disable/', DisableAccount.as_view(),name='disable'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}
                Result Generator
            {% endblock %}
        </title>

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'site/style.css' %}">
        <header>
            <!-- <img src="{% static 'site/logo.jpg' %}" alt="Site Logo"> -->
            <!-- <h1>Result Generator</h1> -->
        </header>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta   name="viewport" content="width=device-width , initial-scale=1">
        <!--[if IE]><script
         src="http://html5shiv.googlecode.com/svn/trunk/html5.js">
        </script><![endif]-->
    </head>

    <body>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                    {{ message }}
                </li>
                {% endfor %}
            </ul>
            {% endif %}
        <div> <!-- container -->
            <header>
                <h1>Result Generator</h1>
            </header>
            
            <main>
                {% block content %}
                    This is defalut content!
                {% endblock %}
            </main>
            
            <div>
                <div>
                    <ul>            
                        {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'dj-auth:logout' %}?next={{ request.path }}">Log Out</a>
                                            
                        </li>
                        {% else %}
                        <li>
                            <a href="{% url 'dj-auth:login' %}?next={{ request.path }}">Log In</a>            
                        </li>
                        <li>
                            <a href="{% url 'dj-auth:create' %}">Register</a>
                        </li>
                        {% endif %}
                        
                    </ul>
                </div>
            </div>
        </div> <!--container-->
    </body>
</html>

templates/home.html
{% extends parent_template|default:"base.html" %}

{% block title %}
    {{ block.super }} -  Home Page
{% endblock title %}

{% block content %}

<!-- 'topScorerOf11' : topScorerOf11,
'topScorerOf12' : topScorerOf12,
'futureExams11' : futureExams11,
'futureExams12' : futureExams12,
'pastExams11' : pastExams11,
'pastExams12' : pastExams12, -->

    <h2> Top Scorer of Standard 11 </h2>
    <div>
        <table>
            {% for academicProfile in topScorerOf11 %}
                    <tr>
                        <td> {{ academicProfile.student.fullName }} </td>
                        <td> {{ academicProfile.totalMarks }} </td>
                    </tr>
            {% endfor %}
        </table>
    </div>


    <h2> Top Scorer of Standard 12 </h2>
    <div>
        <table>
            {% for academicProfile in topScorerOf12 %}
                    <tr>
                        <td> {{ academicProfile.student.fullName }} </td>
                        <td> {{ academicProfile.totalMarks }} </td>
                    </tr>
            {% endfor %}
        </table>
    </div>


    <h2> Past Exam of Standard 11 </h2>
    <div>
        <table>
            {% for exam in pastExams11 %}
                    <tr>
                        <td> {{ exam.examName }} </td>
                        <td> {{ exam.examDate }} </td>
                        <td> {{ exam.standard }} </td>
                    </tr>
            {% endfor %}
        </table>
    </div>


    <h2> Past Exam of Standard 12 </h2>
    <div>
        <table>
            {% for exam in pastExams12 %}
                    <tr>
                        <td> {{ exam.examName }} </td>
                        <td> {{ exam.examDate }} </td>
                        <td> {{ exam.standard }} </td>
                    </tr>
            {% endfor %}
        </table>
    </div>
    
{% endblock content %}